### ISSUE TITLE
Orientation in SSPACE params

### ISSUE THREAD

**Issue by Cantalapiedra** [eead-csic-compbio/chloroplast_assembly_protocol#1]
Is it correct the fixed orientation in SSPACE parameters? Or a TODO?

```
#4.1) create scaffolding parameter file
# lib1 libscaf1.fq libscaf2.fq 4300 0.11 RF
open(PARAMS,">$spaceparamfile") || die "# cannot create $spaceparamfile\n";
print PARAMS "lib1 $pair1file $pair2file $PEinsert 0.2 FR\n";
if($MPfile)
{
  print PARAMS "lib2 $pair1fileMP $pair2fileMP $MPinsert 0.2 FR\n";
}
close(PARAMS);
```

**Comment by eead-csic-compbio** [comment]
As explained in the README.md file, the pipeline expects PE libraries to be FR, while MP libs can be RF (default) and FR. MP reads will be reversed-complemented if required and used as FR internally.
However, the code could be patched to accept any orientations, but that will require some testing.

**Comment by eead-csic-compbio** [comment]
This has been sorted in the new code base after merging the denovo branch.
